### ISSUE TITLE
eccv_demo.py doesn't work

### ISSUE THREAD

**Issue by fred-och-karlek** [wilsonkl/SfM_Init#11]
Traceback (most recent call last):
  File "eccv_demo.py", line 102, in <module>
    sys.exit(run_pipeline())
  File "eccv_demo.py", line 57, in run_pipeline
    global_rot_ids, global_rots = sfminit.solve_global_rotations(edges, pairwise_rotations, cc=cc)
  File "/home/miracle/Desktop/SfM_Init/sfminit/rotsolver.py", line 55, in solve_global_rotations
    cwd=ROT_SOLVER_DIR, stdout=devnul, stderr=devnul)
  File "/home/miracle/anaconda3/envs/sfm/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/miracle/anaconda3/envs/sfm/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/miracle/anaconda3/envs/sfm/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Hi,
I just got this issue and I tried to solve it by adding shell=True, but other error appeared, which is the following,

[eccv_demo] Reading input files
[eccv_demo] Running global rotations solver
[rotsolver:solve_global_rotations] Error! The Matlab rotsolver did not complete.
LOG:
Traceback (most recent call last):
  File "eccv_demo.py", line 102, in <module>
    sys.exit(run_pipeline())
  File "eccv_demo.py", line 57, in run_pipeline
    global_rot_ids, global_rots = sfminit.solve_global_rotations(edges, pairwise_rotations, cc=cc)
  File "/home/miracle/Desktop/SfM_Init/sfminit/rotsolver.py", line 61, in solve_global_rotations
    with open(log, 'r') as fin:
IOError: [Errno 2] No such file or directory: '/tmp/tmpvhh75N/log.txt'

Could you please help me ?

**Comment by wilsonkl** [comment]
Thanks for your interest! 

You're seeing this because you don't have the rotsolver. SfM_Init doesn't ship with a rotation averaging solver. It does include some crude wrappers around Chatterjee and Govindu's Matlab package. (See the SfM_Init Readme for details.) Basically, you'll need to get their rotsolver and unzip it into the "rotsolver" folder.

Alternatively, there are some start-to-finish SfM pipelines that incorporate the 1DSfM components. They may be more user-friendly, since SfM_Init is primarily a reference implementation. I know that 1DSfM is included in Theia-sfm, and I think it is in OpenMVS too.

**Comment by fred-och-karlek** [comment]
Thanks a lot! I will look into that!

**Comment by fred-och-karlek** [comment]
Hi,

I got the matlab code from this link http://www.ee.iisc.ac.in/labs/cvl/research/rotaveraging/ (not the PAMI version) and unzip it into the "rotsolver" folder, but it still doesn't work and give me the same error.... And I check your code snippet but have no clue. 

Do you have any other advice?

Thanks!

**Comment by wilsonkl** [comment]
Are you sure the message is identical?
What happens if you start up a command line and run `matlab --version`?

To get more debugging information, you could try editing line 55 of rotsolver.py to take out the devnull stdout/stderr pipe. That might show a more helpful error message.

**Comment by fred-och-karlek** [comment]
hi,

this is what I got...
![WechatIMG517](https://user-images.githubusercontent.com/43069216/77227880-a4eb6700-6b83-11ea-8c42-33bb02340b06.jpeg)

**Comment by fred-och-karlek** [comment]
and I play around with pipe as you suggested, but it's not very helpful 😢

anyway, I really appreciate your help !

**Comment by wilsonkl** [comment]
Oh! This is very helpful. The rotsolver is crashing. That's happening because it can't find a function called graphconncomp. Looking at [Matlab docs](https://www.mathworks.com/help/bioinfo/ref/graphconncomp.html), it appears that graphconncomp nows lives in the Bioinformatics toolbox for some reason.

**Comment by wilsonkl** [comment]
If you're a Matlab user and want to contribute an alternative that doesn't require this toolbox, I'd happily take a pull request. But it looks like the root problem here is that graphconncomp now lives in a toolbox that you don't seem to have.

**Comment by fred-och-karlek** [comment]
It works now, thank you very much!

And I will look into the Matlab code and see if I can do something.
