### ISSUE TITLE
How can I get the reprojection error from bundle.out?

### ISSUE THREAD

**Issue by sunghoon031** [wilsonkl/SfM_Init#14]
Hi. 
I would like to compute the reprojection error, and to do that, I need to know the measured position of each reconstructed point.
In bundle.out,  it seems that the point entries do not contain the measured position (even though the Bundler's manual says that the point entries should contain the detected positions of the keypoints....)

Could you suggest any sensible method to compute the reprojection error of the reconstructed points?

**Comment by wilsonkl** [comment]
As a global SfM system, 1DSfM doesn't reconstruct 3D point along the way. Points are used on the front end between pairs of views to compute pairwise rotations and translations. A few points are also used to stabilize the translations problem against linear motion. Aside from those few, the final results are computed without triangulating 3D points. That's why none are included in the output.

If you'd like to have 3D points, I suppose you'll need to triangulate them. You could go back to the tracks and coords files to get the information about 2D observations. 

You might consider looking at Theia-sfm, which includes this 1DSfM pipeline, and also has tools built in for triangulating points.

**Comment by sunghoon031** [comment]
I see. How about the reprojection errors from the Bundler output? Was it obtained using the same SIFT keypoints given in coords.txt?

**Comment by wilsonkl** [comment]
Yes, I do believe that the Bundler output is based on those same files. Unfortunately, I think the points were reindexed somewhere along the way, so there's no straightforward way to draw a  correspondence between points in the bundle files and the input tracks/coords.

**Comment by sunghoon031** [comment]
I see. Thanks for the clear explanation! :+1:
